# Generated by Django 5.1.1 on 2024-10-03 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FormApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentForm',
            new_name='StudentModel',
        ),
    ]
